title: My stack
description: popispopis
author: Zdenek Barcaj
github: https://github.com/zdenolab
about: For gallery click TUMBLR icon bellow.
disqus_shortname: zdenolab
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-tumblr-square
      link: "https://zdenolab.tumblr.com"
    - icon: fa-facebook
      link: "https://www.facebook.com/zdenekbarcaj"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/zdenek-barcaj"
    - icon: fa-github
      link: "https://github.com/zdenolab"
      
share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://zdenolab.github.io"
baseurl: ""
paginate: 15
per_page: 15
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
