title: latest posts
description: ....
author: zdenek barcaj
github: https://github.com/zdenolab
about: for gallery just click TMBLR icon bellow.\n\nfeel free to download all my VBA projects.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-tumblr
      link: "https://zdenolab.tumblr.com"
    - icon: fa-facebook
      link: "https://facebook.com"
    - icon: fa-linkedin
      link: "https://linkedin.com"
    - icon: fa-github
      link: "https://github.com/zdenoab"
      
share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://zdenolab.github.io"
baseurl: ""
paginate: 20
per_page: 10
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
